allComands:dict = {
    "~help" : "Mostrar comandos do bot\n.", 
    "~spam <n> <mensagem>" : "spamar uma mensagem n vezes no servidor\n.", 
    "~spanP <n> <@pessoa> <mensagem>" : "Spama um pessoa no privado n vezes de maneira anonima\n", 
    "~status <jogo, musica ou filme> <mensagem>" : "Alterar mensagem que aparece no status do bot\n.", 
    "~copypasta <index da copypasta>(opcional)" : "Envia uma copypasta retirado diretamente do nosso incrível banco de dados\n.", 
    "~alerta <mensagem>" : "Envia uma mensagem de alerta marcando todos, em todos os canais do server\n.", 
    "~roll" : "Brinque de roleta russa e remova alguem aleatoriamente do canal\n.", 
    "~purge" : "Diversão! Manda todo mundo que tá na call pro caralho. \n.", 
    "~mute @pessoa" : "Tira o som da pessoa em todos os servidores possíveis, por que pau no cu dessa pessoa em especial. \n.", 
    "~unmute @pessoa" : "Muten't.\n.", 
    "~headphone @pessoa" : "Tira os 5 sentidos da pessoa na call\n.", 
    "~unheadphone @pessoa" : "Volta o som e o mic da pessoa. Booooo\n.", 
    "~silence" : "Cala a boca de todo mundo\n.", 
    "~unsilence" : "!Silence.\n.", 
    "~ban @pessoa" : "Desconecta a pessoa do canal de voz.\n"
}

mensagensImportantes:list = [
    "#CassioVitima",
    "#GuiChato",
    "#GuiGado",
    "#GuiAtrasado",
    "Palmeiras n tem mundial",
    "#CassioCulpado",
    "Raquel Filha da Puta",
    "Calebe Filha da Puta",
    "#MarcheloFarmacia",
    "#CassioMedroso",
    "#Honey",
    "SuaTiaEhCasada?",
    "bitch",
    "AOBA",
    "Never gonna give you up",
    "69",
    "420",
    "#Kassio",
    "#CassioS2Katia",
    "OH",
    "ALOU",
    "_/\o_", 
    "VIVA AO DEUS LUA", 
    "SALUDEM AO DEUS LUA",
    "#monstro"
]