allComands:dict = {
    "~help"                                         : "Mostrar comandos do bot.\n", 
    "~mensagem"                                     : "Manda uma mensagem aleatória inpiradora.\n",
    "~flood <n> <mensagem>"                         : "Spama uma mensagem n vezes no servidor.\n", 
    "~floodPV <n> <@pessoa> <mensagem>"             : "Spama uma mensagem no privado n vezes de maneira anônima.\n",
    "~status <jogo, musica ou filme> <mensagem>"    : "Alterar mensagem que aparece no status do bot.\n", 
    "~copypasta <index da copypasta>(opcional)"     : "Envia uma copypasta retirado diretamente do nosso incrível banco de dados.\n", 
    "~yall <mensagem>"                              : "Envia uma mensagem de alerta marcando todos, em todos os canais do server.\n", 
    "~roullete"                                     : "Brinque de roleta russa e remova alguem aleatoriamente do canal.\n", 
    "~purge"                                        : "Diversão! Manda todo mundo que tá na call pro caralho.\n", 
    "~erradicate"                                   : "Oh não! Um tiroteio ocorreu no server, ninguém em call permaneceu.\n",
    "~deafen @pessoa"                               : "Tira os 5 sentidos da pessoa na call.\n", 
    "~undeafen @pessoa"                             : "Volta o som e o mic da pessoa. Booooo!!\n", 
    "~silence"                                      : "Cala a boca de todo mundo.\n", 
    "~unsilence"                                    : "!Silence.\n", 
    "~shake <@pessoa>"                              : "A pessoa esta confusa e fica mudando de canal aleatoriamente.\n",
    "~earthquake"                                   : "Terremoto! Todo mundo esta indo p/ todo lugar.\n",
    "~ban @pessoa"                                  : "Desconecta a pessoa do canal de voz.\n",
    "~shout NomeDoArquivo"                          : "Reproduz um áudio prestativo e inspirador.\n"
}